Repository neelshah2409/Cartoonist, pull requests merged in 2023-01, with the labels that each got.

#28 Create tree_design.py
  tree_design.py
Labels: codepeak 22, points:5

#26 created spongebob design
  sponge_bob.py
Labels: codepeak 22, points:5

#72 added new Mandela design
  mandela3.py
Labels: codepeak 22, points:5

#71 Create Helloween.py
  Helloween.py
Labels: codepeak 22, point:10

#69 Create USA_flag.py
  USA_flag.py
Labels: codepeak 22, points:5

#33 Create Five_shapes.py
  Five_shapes.py
Labels: codepeak 22, point:10

#37 Create spiral_circle.py
  spiral_circle.py
Labels: codepeak 22, points:5

#67 Create spider_web.py
  spider_web.py
Labels: codepeak 22, points:5

#65 Create Virus.py
  Virus.py
Labels: codepeak 22, point:10

#63 Create Chrome_logo.py
  Chrome_logo.py
Labels: codepeak 22, points:5

#61 Create Dell_logo.py
  Dell_logo.py
Labels: codepeak 22, points:5

#57 Create cred_logo.py
  cred_logo.py
Labels: codepeak 22, points:5

#55 Create mickey_mouse.py
  mickey_mouse.py
Labels: codepeak 22, points:5

#53 Create spotify_logo.py
  spotify_logo.py
Labels: codepeak 22, points:5

#51 Create google_drive_logo.py
  google_drive_logo.py
Labels: codepeak 22, points:5

#49 Create Goku.py
  Goku.py
Labels: codepeak 22, points:10

#43 Create tiktok_logo.py
  tiktok_logo.py
Labels: codepeak 22, points:5

#41 Create animation_clock.py
  animation_clock.py
Labels: codepeak 22, points:5

#74 Birthday cake
  birthday_cake.py
Labels: codepeak 22, points:5

#89 Added circular design
  circular_design.py
  sharingan_logo.py
Labels: codepeak 22, points:5

#82 added mercedes logo
  mercedes_benz.py
Labels: codepeak 22, points:5

#92 added apple logo
  apple.py
Labels: codepeak 22, points:5

#99 Create Dog.py
  Dog.py
Labels: codepeak 22, points:5

#102 Create France_flag.py
  France_flag.py
Labels: codepeak 22, points:5

#112 Create Pakistan_flag.py
  Pakistan_flag.py
Labels: codepeak 22, points:10

#110 Create Turkey_flag.py
  Turkey_flag.py
Labels: codepeak 22, points:10

#108 Create Portugal_flag.py
  Portugal_flag.py
Labels: codepeak 22, points:5

#93 added 3 car logos(Volkswagen, Tesla and Audi
  audi_logo.py
  tesla_logo.py
  volkswagon_logo.py
Labels: codepeak 22, points:10

#94 Added windows logo
  Microsoft.py
  Windows10_logo.py
  graph_paper.py
Labels: codepeak 22, points:5

#122 added chess.py
  chess.py
Labels: codepeak 22, points:5

#129 Created Youtube Logo
  Deathly Hallows
  youtube_logo.py
Labels: codepeak 22, points:5

#126 added circular_design.py
  circular_design.py
Labels: codepeak 22, points:5

#90 Added spiral design
  spiral_design.py
Labels: codepeak 22, points:5

#133 added BMW logo
  bmw_logo.py
Labels: codepeak 22, points:5

#134 Create Japan_flag.py
  Japan_flag.py
Labels: codepeak 22, points:5

#138 added mitsubushi logo
  mitsubushi_logo.py
Labels: codepeak 22, points:5

#132 added pikachu.py
  pikachu.py
Labels: codepeak 22, points:10

#142 added honda logo
  honda_logo.py
Labels: codepeak 22, points:5

#140 added doraemon.py
  doraemon.py
Labels: codepeak 22, points:10

#149 Create gfg_logo.py
  LOGO/gfg_logo.py
Labels: codepeak 22, points:10

#148 Create panda.py
  Animals/panda.py
Labels: codepeak 22, points:10

#151 Create ninja_twist.py
  Designs/ninja_twist.py
Labels: codepeak 22, points:10

#150 added lexus logo
  lexus_logo.py
Labels: codepeak 22, points:5

#147 added amomgus.py
  amongus.py
Labels: codepeak 22, points:5

#158 Create pubg_logo.py
  LOGO/pubg_logo.py
Labels: codepeak 22, points:5

#165 Create spider_man
  Anime characters/spider_man.py
Labels: codepeak 22, points:10

#164 Create Christmas_tree.py
  Others/Christmas_tree.py
Labels: codepeak 22, points:5

#161 Create car.py
  Things/car.py
Labels: codepeak 22, points:5

#160 Create free_fire_logo.py
  LOGO/free_fire_logo.py
Labels: codepeak 22, points:10

#156 added renault logo
  renault_logo.py
Labels: codepeak 22, points:5

#166 Create radha_krishna.py
  Others/radha_krishna.py
Labels: codepeak 22, points:10

#167 Create snowman.py
  Others/snowman.py
Labels: codepeak 22, points:5

#168 Create cat.py
  Animals/cat.py
Labels: codepeak 22, points:5

#155 Mini cooper logo
  mini_cooper_logo.py
Labels: codepeak 22, points:5

#153 added squares.py
  Designs/squares.py
Labels: codepeak 22, points:5

#169 Create Bird.py
  Animals/Bird.py
Labels: codepeak 22, points:10
